### ISSUE TITLE
Location updates combined storage (redis + postgres)

### ISSUE THREAD

**Issue by kepkap** [openmarketplaceengine/openmarketplaceengine#109]
10000 drivers send location updates every 15 seconds.
each location update is stored in redis GEO_POS key area key + workerId member.

Additionally we need to store location updates in postgres, but for the purpose of keeping routes history.  Async, every 1 min (??)

Each location update triggers tollgate crossing detection. Crossing once detected persisted in database. 

TODO: design and implement solution to achieve the subj.

**Comment by kepkap** [comment]
our worker locations can be used in google APIs, like https://developers.google.com/maps/documentation/distance-matrix/distance-matrix

**Comment by kevinmichaelchen** [comment]
Currently we're using Redis as a write-through, synchronously writing to Postgres and then Redis:
```go
crossingHandlers: []detector.Handler{persistCrossing, publishCrossing},
```

This has been discussed before/elsewhere, but writing it here for clear documentation:

Eventually I think we may want to follow up with a more async write-back/write-behind approach, à la the [Helsinki Bus App](https://redis.com/blog/create-a-real-time-vehicle-tracking-system-with-redis/), where we use a "Redis Streams to RedisGears" flow.

Writing to Redis Streams would look something like this:
```go
pipe.XAdd(
    ctx, &redis.XAddArgs{
        Stream: "locations",
        Values: []interface{}{
            "lat", e.Lat,
            "lng", e.Lng,
            "time", e.Timestamp,
        },
    },
)
```

Then we'd need a [custom Docker image](https://github.com/redis-developer/expert-garbanzo/blob/master/redis/Dockerfile) for Redis that brings in a RedisGears function that implements write-back behavior (found [here](https://github.com/redis-developer/expert-garbanzo/blob/master/redis/stream_writebehind.py)).
