### ISSUE TITLE
GetAvailableJobs API

### ISSUE THREAD

**Issue by jasonprado** [openmarketplaceengine/openmarketplaceengine#112]
- Return all jobs that are in the future and are not claimed
- Take in a worker_id; the view will ultimately be specific to the worker
- Build ranking as a function of worker location
- Take an argument for time window to query within

Geo model:
- Support flexible geo backends: crow-fly distance, zip-to-zip (or hex-to-hex) ETAs, Google Maps DistanceMatrix API

**Comment by kepkap** [comment]
we had a discussion in slack where decided to switch over to PostGIS extension to use geographic optimised  distance range  queries.   

for local dev we are going to use docker pull postgis/postgis:14-3.2-alpine
and for production extension will be installed separately. 

All location lat lon storage will be changed accordingly. 

cc @vlkolmakov  @kevinmichaelchen

**Comment by vlkolmakov** [comment]
Thanks for the info. I'll test locally and we'll see what solution is the most appropriate.

**Comment by kepkap** [comment]
initial version done, other issues have been raised.
