### ISSUE TITLE
Define type for worker identifier

### ISSUE THREAD

**Issue by jasonprado** [openmarketplaceengine/openmarketplaceengine#8]

**Comment by kevinmichaelchen** [comment]
If unpredictability in IDs isn't important, we could consider https://github.com/rs/xid, a compact, time-based, k-ordered ID.

There are 16 of these time-based implementations cited in this [RFC](https://datatracker.ietf.org/doc/html/draft-peabody-dispatch-new-uuid-format) for time-based UUIDs:
> First, most of the existing UUID versions such as UUIDv4
   have poor database index locality.  Meaning new values created in
   succession are not close to each other in the index and thus require
   inserts to be performed at random locations.  The negative
   performance effects of which on common structures used for this
   (B-tree and its variants) can be dramatic.  As such newly inserted
   values SHOULD be time-ordered to address this.
>
> An inspection of these implementations details the following trends
   that help define this standard:
>
>      - Timestamps MUST be k-sortable.  That is, values within or close
>      to the same timestamp are ordered properly by sorting algorithms.
>      - Timestamps SHOULD be big-endian with the most-significant bits
>      of the time embedded as-is without reordering.
>      - Timestamps SHOULD utilize millisecond precision and Unix Epoch
>      as timestamp source.  Although, there is some variation to this
>      among implementations depending on the application requirements.
>      - The ID format SHOULD be Lexicographically sortable while in the
>      textual representation.
>      - IDs MUST ensure proper embedded sequencing to facilitate sorting
>      when multiple UUIDs are created during a given timestamp.
>      - IDs MUST NOT require unique network identifiers as part of
>      achieving uniqueness.
>      - Distributed nodes MUST be able to create collision resistant
>      Unique IDs without consulting a centralized resource.
